after_failure:
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
before_script:
  - cp config/initializers/myusa.rb.example config/initializers/myusa.rb
install:
  - bundle install --without development
language: ruby
notifications:
  email:
    recipients:
      - justin.grevich@gsa.gov
script: 
  - bundle exec rake spec
rvm:
  - 1.9.3